/* questions-gk.js — verified General Knowledge questions (90 total: 30 per level).
   Format: { q, options:[4], answer:index, explanation }
   Add more freely in the same shape. */
(function (global) {
  var GK = {
    easy: [
      { q: 'What is the capital of India?', options: ['Mumbai', 'New Delhi', 'Kolkata', 'Chennai'], answer: 1, explanation: 'New Delhi is the capital of India.' },
      { q: 'Which is the national animal of India?', options: ['Lion', 'Elephant', 'Tiger', 'Leopard'], answer: 2, explanation: 'The Royal Bengal Tiger is India\u2019s national animal.' },
      { q: 'How many states are there in India?', options: ['27', '28', '29', '30'], answer: 1, explanation: 'India has 28 states and 8 union territories.' },
      { q: 'What is the currency of Japan?', options: ['Yuan', 'Won', 'Yen', 'Ringgit'], answer: 2, explanation: 'The currency of Japan is the Yen.' },
      { q: 'Which gas do plants absorb from the air?', options: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'], answer: 2, explanation: 'Plants absorb carbon dioxide for photosynthesis.' },
      { q: 'Which is the national bird of India?', options: ['Parrot', 'Peacock', 'Sparrow', 'Eagle'], answer: 1, explanation: 'The Indian Peacock is the national bird.' },
      { q: 'Which is the largest planet in our solar system?', options: ['Saturn', 'Earth', 'Jupiter', 'Neptune'], answer: 2, explanation: 'Jupiter is the largest planet.' },
      { q: 'The Taj Mahal is located in which city?', options: ['Delhi', 'Agra', 'Jaipur', 'Lucknow'], answer: 1, explanation: 'The Taj Mahal is in Agra, Uttar Pradesh.' },
      { q: 'Who was the first Prime Minister of India?', options: ['Sardar Patel', 'Jawaharlal Nehru', 'Rajendra Prasad', 'B. R. Ambedkar'], answer: 1, explanation: 'Jawaharlal Nehru was the first PM of India.' },
      { q: 'How many players are there in a cricket team?', options: ['9', '10', '11', '12'], answer: 2, explanation: 'A cricket team has 11 players.' },
      { q: 'The Red Fort is located in which city?', options: ['Agra', 'Delhi', 'Hyderabad', 'Mumbai'], answer: 1, explanation: 'The Red Fort is in Delhi.' },
      { q: 'Which is the national flower of India?', options: ['Rose', 'Lotus', 'Sunflower', 'Marigold'], answer: 1, explanation: 'The Lotus is India\u2019s national flower.' },
      { q: 'Which festival is known as the festival of lights?', options: ['Holi', 'Diwali', 'Eid', 'Onam'], answer: 1, explanation: 'Diwali is the festival of lights.' },
      { q: 'How many bones are there in an adult human body?', options: ['198', '206', '212', '220'], answer: 1, explanation: 'An adult human body has 206 bones.' },
      { q: 'Which is the longest river in India?', options: ['Yamuna', 'Godavari', 'Ganga', 'Narmada'], answer: 2, explanation: 'The Ganga is the longest river within India.' },
      { q: 'Which is the smallest continent?', options: ['Europe', 'Australia', 'Antarctica', 'South America'], answer: 1, explanation: 'Australia is the smallest continent.' },
      { q: 'How many days are there in a leap year?', options: ['364', '365', '366', '367'], answer: 2, explanation: 'A leap year has 366 days.' },
      { q: 'Which planet is known as the Red Planet?', options: ['Venus', 'Mars', 'Jupiter', 'Mercury'], answer: 1, explanation: 'Mars is called the Red Planet.' },
      { q: 'What is the chemical formula for water?', options: ['CO2', 'O2', 'H2O', 'NaCl'], answer: 2, explanation: 'Water is H2O \u2014 two hydrogen and one oxygen atom.' },
      { q: 'Which is the largest country in the world by area?', options: ['China', 'USA', 'Russia', 'Canada'], answer: 2, explanation: 'Russia is the largest country by area.' },
      { q: 'How many continents are there on Earth?', options: ['5', '6', '7', '8'], answer: 2, explanation: 'There are 7 continents.' },
      { q: 'Which is the fastest land animal?', options: ['Lion', 'Cheetah', 'Horse', 'Leopard'], answer: 1, explanation: 'The cheetah is the fastest land animal.' },
      { q: 'What is the capital of France?', options: ['Rome', 'Berlin', 'Paris', 'Madrid'], answer: 2, explanation: 'Paris is the capital of France.' },
      { q: 'Which organ pumps blood in the human body?', options: ['Lungs', 'Brain', 'Heart', 'Liver'], answer: 2, explanation: 'The heart pumps blood.' },
      { q: 'How many colours are there in a rainbow?', options: ['5', '6', '7', '8'], answer: 2, explanation: 'A rainbow has 7 colours (VIBGYOR).' },
      { q: 'Which gas do humans need to breathe to survive?', options: ['Carbon dioxide', 'Oxygen', 'Nitrogen', 'Helium'], answer: 1, explanation: 'Humans breathe oxygen to survive.' },
      { q: 'What is the freezing point of water in Celsius?', options: ['0\u00b0C', '10\u00b0C', '32\u00b0C', '100\u00b0C'], answer: 0, explanation: 'Water freezes at 0\u00b0C.' },
      { q: 'Which is the tallest mountain in the world?', options: ['K2', 'Mount Everest', 'Kangchenjunga', 'Makalu'], answer: 1, explanation: 'Mount Everest is the tallest mountain.' },
      { q: 'How many sides does a triangle have?', options: ['2', '3', '4', '5'], answer: 1, explanation: 'A triangle has 3 sides.' },
      { q: 'Which is the national fruit of India?', options: ['Banana', 'Apple', 'Mango', 'Orange'], answer: 2, explanation: 'The mango is India\u2019s national fruit.' }
    ],
    medium: [
      { q: 'Who wrote the national anthem of India?', options: ['Bankim Chandra', 'Rabindranath Tagore', 'Sarojini Naidu', 'Subhas Bose'], answer: 1, explanation: 'Rabindranath Tagore wrote \u201cJana Gana Mana\u201d.' },
      { q: 'Who was the first woman Prime Minister of India?', options: ['Sonia Gandhi', 'Pratibha Patil', 'Indira Gandhi', 'Sushma Swaraj'], answer: 2, explanation: 'Indira Gandhi was India\u2019s first woman PM.' },
      { q: 'Where is the headquarters of the United Nations?', options: ['Geneva', 'Paris', 'New York', 'London'], answer: 2, explanation: 'The UN headquarters is in New York City.' },
      { q: 'Which Indian state has the largest area?', options: ['Madhya Pradesh', 'Maharashtra', 'Rajasthan', 'Uttar Pradesh'], answer: 2, explanation: 'Rajasthan is the largest state by area.' },
      { q: 'The Tropic of Cancer passes through how many Indian states?', options: ['6', '7', '8', '9'], answer: 2, explanation: 'It passes through 8 Indian states.' },
      { q: 'In which year was the Reserve Bank of India established?', options: ['1925', '1935', '1947', '1950'], answer: 1, explanation: 'The RBI was established in 1935.' },
      { q: 'Which Article of the Constitution deals with the Right to Equality?', options: ['Article 12', 'Article 14', 'Article 19', 'Article 21'], answer: 1, explanation: 'Article 14 guarantees equality before law.' },
      { q: 'In which year did the Jallianwala Bagh massacre take place?', options: ['1909', '1919', '1929', '1942'], answer: 1, explanation: 'The massacre occurred in 1919.' },
      { q: 'Who is known as the Father of the Indian Constitution?', options: ['Mahatma Gandhi', 'B. R. Ambedkar', 'Nehru', 'Rajendra Prasad'], answer: 1, explanation: 'Dr. B. R. Ambedkar chaired the drafting committee.' },
      { q: 'Which is the smallest state of India by area?', options: ['Sikkim', 'Goa', 'Tripura', 'Nagaland'], answer: 1, explanation: 'Goa is the smallest state by area.' },
      { q: 'Which vitamin is produced when skin is exposed to sunlight?', options: ['Vitamin A', 'Vitamin C', 'Vitamin D', 'Vitamin K'], answer: 2, explanation: 'Sunlight helps the body make Vitamin D.' },
      { q: 'How many houses does the Indian Parliament have?', options: ['One', 'Two', 'Three', 'Four'], answer: 1, explanation: 'Parliament has two houses: Lok Sabha and Rajya Sabha.' },
      { q: 'Who was the first Indian to travel to space?', options: ['Kalpana Chawla', 'Rakesh Sharma', 'Sunita Williams', 'Vikram Sarabhai'], answer: 1, explanation: 'Rakesh Sharma went to space in 1984.' },
      { q: 'The Dandi March was led by whom?', options: ['Nehru', 'Mahatma Gandhi', 'Patel', 'Bhagat Singh'], answer: 1, explanation: 'Gandhi led the Dandi (Salt) March in 1930.' },
      { q: 'Which is the largest ocean on Earth?', options: ['Atlantic', 'Indian', 'Pacific', 'Arctic'], answer: 2, explanation: 'The Pacific Ocean is the largest.' },
      { q: 'Who invented the telephone?', options: ['Thomas Edison', 'Alexander Graham Bell', 'Nikola Tesla', 'Guglielmo Marconi'], answer: 1, explanation: 'Alexander Graham Bell invented the telephone.' },
      { q: 'Which is the largest hot desert in the world?', options: ['Gobi', 'Thar', 'Sahara', 'Kalahari'], answer: 2, explanation: 'The Sahara is the largest hot desert.' },
      { q: 'In which year did India gain independence?', options: ['1942', '1945', '1947', '1950'], answer: 2, explanation: 'India became independent in 1947.' },
      { q: 'Who painted the Mona Lisa?', options: ['Michelangelo', 'Leonardo da Vinci', 'Raphael', 'Picasso'], answer: 1, explanation: 'Leonardo da Vinci painted the Mona Lisa.' },
      { q: 'Which river is traditionally considered the longest in the world?', options: ['Amazon', 'Nile', 'Ganga', 'Yangtze'], answer: 1, explanation: 'The Nile is traditionally regarded as the longest river.' },
      { q: 'What is the capital of Australia?', options: ['Sydney', 'Melbourne', 'Canberra', 'Perth'], answer: 2, explanation: 'Canberra is the capital of Australia.' },
      { q: 'Which planet is closest to the Sun?', options: ['Venus', 'Earth', 'Mercury', 'Mars'], answer: 2, explanation: 'Mercury is closest to the Sun.' },
      { q: 'Who wrote the play \u201cRomeo and Juliet\u201d?', options: ['Charles Dickens', 'William Shakespeare', 'John Keats', 'Leo Tolstoy'], answer: 1, explanation: 'William Shakespeare wrote Romeo and Juliet.' },
      { q: 'The Great Wall is located in which country?', options: ['Japan', 'China', 'India', 'Mongolia'], answer: 1, explanation: 'The Great Wall is in China.' },
      { q: 'Which metal is liquid at room temperature?', options: ['Iron', 'Mercury', 'Lead', 'Zinc'], answer: 1, explanation: 'Mercury is liquid at room temperature.' },
      { q: 'Which is the largest mammal in the world?', options: ['Elephant', 'Blue whale', 'Giraffe', 'Hippopotamus'], answer: 1, explanation: 'The blue whale is the largest mammal.' },
      { q: 'What does \u201cwww\u201d stand for?', options: ['World Web Wide', 'World Wide Web', 'Wide World Web', 'Web Wide World'], answer: 1, explanation: 'WWW stands for World Wide Web.' },
      { q: 'Which Indian city is known as the \u201cPink City\u201d?', options: ['Udaipur', 'Jaipur', 'Jodhpur', 'Jaisalmer'], answer: 1, explanation: 'Jaipur is called the Pink City.' },
      { q: 'Who is known as the \u201cMissile Man of India\u201d?', options: ['Vikram Sarabhai', 'A. P. J. Abdul Kalam', 'Homi Bhabha', 'C. V. Raman'], answer: 1, explanation: 'Dr. A. P. J. Abdul Kalam is the Missile Man of India.' },
      { q: 'Which is the national aquatic animal of India?', options: ['Blue whale', 'River dolphin', 'Shark', 'Turtle'], answer: 1, explanation: 'The Gangetic river dolphin is the national aquatic animal.' }
    ],
    hard: [
      { q: 'Which constitutional amendment is called the \u201cMini Constitution\u201d?', options: ['24th', '42nd', '44th', '52nd'], answer: 1, explanation: 'The 42nd Amendment (1976) is called the Mini Constitution.' },
      { q: 'In which year was the Battle of Plassey fought?', options: ['1757', '1764', '1772', '1799'], answer: 0, explanation: 'The Battle of Plassey took place in 1757.' },
      { q: 'Who founded the Arya Samaj?', options: ['Raja Ram Mohan Roy', 'Swami Vivekananda', 'Dayananda Saraswati', 'Swami Shraddhanand'], answer: 2, explanation: 'Swami Dayananda Saraswati founded Arya Samaj in 1875.' },
      { q: 'Which planet is known as the Morning Star?', options: ['Mars', 'Venus', 'Mercury', 'Jupiter'], answer: 1, explanation: 'Venus is called the Morning Star.' },
      { q: 'The \u201cDoctrine of Lapse\u201d was introduced by which Governor-General?', options: ['Lord Curzon', 'Lord Dalhousie', 'Lord Canning', 'Lord Ripon'], answer: 1, explanation: 'Lord Dalhousie introduced the Doctrine of Lapse.' },
      { q: 'Which Article of the Constitution abolishes untouchability?', options: ['Article 15', 'Article 17', 'Article 19', 'Article 21'], answer: 1, explanation: 'Article 17 abolishes untouchability.' },
      { q: 'Where is the headquarters of ISRO located?', options: ['Hyderabad', 'Chennai', 'Bengaluru', 'Pune'], answer: 2, explanation: 'ISRO is headquartered in Bengaluru.' },
      { q: 'Who discovered the cell?', options: ['Robert Brown', 'Robert Hooke', 'Charles Darwin', 'Louis Pasteur'], answer: 1, explanation: 'Robert Hooke discovered the cell in 1665.' },
      { q: 'Which Mughal emperor built the Red Fort?', options: ['Akbar', 'Babur', 'Shah Jahan', 'Aurangzeb'], answer: 2, explanation: 'Shah Jahan built the Red Fort in Delhi.' },
      { q: 'In which year was the Quit India Movement launched?', options: ['1930', '1935', '1942', '1945'], answer: 2, explanation: 'The Quit India Movement began in 1942.' },
      { q: 'Which is the largest gland in the human body?', options: ['Pancreas', 'Liver', 'Thyroid', 'Pituitary'], answer: 1, explanation: 'The liver is the largest gland.' },
      { q: 'In which year did the Simon Commission come to India?', options: ['1919', '1928', '1935', '1942'], answer: 1, explanation: 'The Simon Commission arrived in 1928.' },
      { q: 'Who was the first Governor-General of independent India?', options: ['C. Rajagopalachari', 'Lord Mountbatten', 'Rajendra Prasad', 'Lord Wavell'], answer: 1, explanation: 'Lord Mountbatten was the first Governor-General after 1947.' },
      { q: 'In which year did the Chauri Chaura incident occur?', options: ['1919', '1920', '1922', '1930'], answer: 2, explanation: 'The Chauri Chaura incident happened in 1922.' },
      { q: 'Which river is known as the \u201cSorrow of Bihar\u201d?', options: ['Ganga', 'Kosi', 'Son', 'Gandak'], answer: 1, explanation: 'The Kosi river is called the Sorrow of Bihar.' },
      { q: 'Who was the first President of the United States?', options: ['Abraham Lincoln', 'George Washington', 'Thomas Jefferson', 'John Adams'], answer: 1, explanation: 'George Washington was the first US President.' },
      { q: 'In which year did World War II end?', options: ['1939', '1942', '1945', '1948'], answer: 2, explanation: 'World War II ended in 1945.' },
      { q: 'What is the chemical symbol for gold?', options: ['Go', 'Gd', 'Au', 'Ag'], answer: 2, explanation: 'The symbol for gold is Au.' },
      { q: 'Who developed the theory of relativity?', options: ['Isaac Newton', 'Albert Einstein', 'Galileo Galilei', 'Niels Bohr'], answer: 1, explanation: 'Albert Einstein developed the theory of relativity.' },
      { q: 'Which is the smallest country in the world?', options: ['Monaco', 'Maldives', 'Vatican City', 'San Marino'], answer: 2, explanation: 'Vatican City is the smallest country.' },
      { q: 'The headquarters of WHO is located in which city?', options: ['New York', 'Geneva', 'Paris', 'Vienna'], answer: 1, explanation: 'The WHO is headquartered in Geneva.' },
      { q: 'Who was the first woman to win a Nobel Prize?', options: ['Mother Teresa', 'Marie Curie', 'Rosalind Franklin', 'Dorothy Hodgkin'], answer: 1, explanation: 'Marie Curie was the first woman to win a Nobel Prize.' },
      { q: 'In which year did the first man land on the Moon?', options: ['1965', '1969', '1971', '1975'], answer: 1, explanation: 'The first Moon landing was in 1969.' },
      { q: 'Which Indian won the first Nobel Prize?', options: ['C. V. Raman', 'Rabindranath Tagore', 'Mother Teresa', 'Amartya Sen'], answer: 1, explanation: 'Rabindranath Tagore won the Nobel Prize for Literature in 1913.' },
      { q: 'What is known as the powerhouse of the cell?', options: ['Nucleus', 'Mitochondria', 'Ribosome', 'Cytoplasm'], answer: 1, explanation: 'Mitochondria are the powerhouse of the cell.' },
      { q: 'Which acid is found in the human stomach?', options: ['Sulphuric acid', 'Hydrochloric acid', 'Nitric acid', 'Acetic acid'], answer: 1, explanation: 'The stomach contains hydrochloric acid.' },
      { q: 'The Eiffel Tower is located in which city?', options: ['London', 'Rome', 'Paris', 'Berlin'], answer: 2, explanation: 'The Eiffel Tower is in Paris.' },
      { q: 'Who founded Microsoft?', options: ['Steve Jobs', 'Bill Gates', 'Mark Zuckerberg', 'Larry Page'], answer: 1, explanation: 'Bill Gates co-founded Microsoft (with Paul Allen).' },
      { q: 'Which is the hardest natural substance on Earth?', options: ['Iron', 'Quartz', 'Diamond', 'Granite'], answer: 2, explanation: 'Diamond is the hardest natural substance.' },
      { q: 'In which year did the Indian Constitution come into effect?', options: ['1947', '1948', '1949', '1950'], answer: 3, explanation: 'The Constitution came into effect on 26 January 1950.' }
    ]
  };
  global.QUESTIONS_GK = GK;
})(window);